openapi: 3.0.3
info:
  title: OrganizationUnit Management API
  version: "1.0"
  description: This API is used to manage organization units.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://{host}:{port}
    variables:
      host:
        default: "localhost"
      port:
        default: "8090"

tags:
  - name: organization-units
    description: Operations related to organization unit management

paths:
  /organization-units:
    get:
      tags:
        - organization-units
      summary: List organization units
      responses:
        "200":
          description: List of organization units
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrganizationUnitBasic'
              example:
                - id: "afc77cfd-620b-4cf0-a31c-7377b0ea8902"
                  name: "Engineering"
                  description: "Engineering Unit"
                  parent: null
                  organizationUnits:
                    - "6b59f277-fd79-40b1-afca-dce75d3709f7"
                - id: "b7c40de6-95cd-4c45-8725-9c7cb5b9cafd"
                  name: "Sales"
                  description: "Sales Unit"
                  parent: null
                  organizationUnits: []
        "500":
          description: Internal server error

    post:
      tags:
        - organization-units
      summary: Create a new organization unit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrganizationUnitRequest'
            examples:
              root-ou:
                summary: Root organization unit
                value:
                  name: "Engineering"
                  description: "Engineering Unit"
                  parent: null
              nested-ou:
                summary: Nested organization unit
                value:
                  name: "Frontend Team"
                  description: "Handles UI/UX work"
                  parent: "afc77cfd-620b-4cf0-a31c-7377b0ea8902"
      responses:
        "201":
          description: Organization unit created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationUnit'
              examples:
                root-ou:
                  summary: Root organization unit
                  value:
                    id: "afc77cfd-620b-4cf0-a31c-7377b0ea8902"
                    name: "Engineering"
                    description: "Engineering Unit"
                    parent: null
                nested-ou:
                  summary: Nested organization unit
                  value:
                    id: "4d4cb83a-9bb8-4fd7-970e-36b65f9c8ea4"
                    name: "Frontend Team"
                    description: "Handles UI/UX work"
                    parent: "afc77cfd-620b-4cf0-a31c-7377b0ea8902"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                invalid-request:
                  summary: Invalid request format
                  value:
                    code: "OU-1001"
                    message: "Invalid request format"
                    description: "The request body is malformed, contains invalid data, or required fields are missing/empty"
                parent-not-found:
                  summary: Parent organization unit not found
                  value:
                    code: "OU-1005"
                    message: "Parent organization unit not found"
                    description: "Parent organization unit not found"
                circular-dependency:
                  summary: Circular dependency detected
                  value:
                    code: "OU-1007"
                    message: "Circular dependency detected"
                    description: "Setting this parent would create a circular dependency"
        "409":
          description: Organization unit name conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: "OU-1004"
                message: "Organization unit name conflict"
                description: "An organization unit with the same name exists under the same parent"
        "500":
          description: Internal server error

  /organization-units/{id}:
    get:
      tags:
        - organization-units
      summary: Get an organization unit by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Organization unit details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationUnit'
              example:
                id: "afc77cfd-620b-4cf0-a31c-7377b0ea8902"
                name: "Engineering Team"
                description: "Engineering unit that handles all engineering tasks"
                parent: null
                users:
                  - "3f9d5c8e-3c56-4f09-a1db-bb3d5e3f4b5d"
                  - "9f4bc2ee-8d1e-4e21-a3b4-17d9b612e320"
                  - "20eb225a-e8c3-4ccf-9d47-b659e26014d7"
                groups:
                  - "c2a4f62d-7c79-46f2-b2de-8e8cb4f1c456"
                  - "8a8e4fa2-2e55-478d-bf0f-4a2ddaf9ee7d"
                organizationUnits:
                  - "6b59f277-fd79-40b1-afca-dce75d3709f7"
        "404":
          description: Organization unit not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: "OU-1003"
                message: "Organization unit not found"
                description: "The organization unit with the specified id does not exist"
        "500":
          description: Internal server error

    put:
      tags:
        - organization-units
      summary: Update an organization unit by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateOrganizationUnitRequest'
            example:
              name: "Engineering Team"
              description: "Engineering unit that handles all engineering tasks"
              parent: null
      responses:
        "200":
          description: Organization unit updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationUnit'
              example:
                id: "afc77cfd-620b-4cf0-a31c-7377b0ea8902"
                name: "Engineering Team"
                description: "Engineering unit that handles all engineering tasks"
                parent: null
                users:
                  - "3f9d5c8e-3c56-4f09-a1db-bb3d5e3f4b5d"
                  - "9f4bc2ee-8d1e-4e21-a3b4-17d9b612e320"
                  - "20eb225a-e8c3-4ccf-9d47-b659e26014d7"
                groups:
                  - "c2a4f62d-7c79-46f2-b2de-8e8cb4f1c456"
                  - "8a8e4fa2-2e55-478d-bf0f-4a2ddaf9ee7d"
                organizationUnits:
                  - "6b59f277-fd79-40b1-afca-dce75d3709f7"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                invalid-request:
                  summary: Invalid request format
                  value:
                    code: "OU-1001"
                    message: "Invalid request format"
                    description: "The request body is malformed, contains invalid data, or required fields are missing/empty"
                parent-not-found:
                  summary: Parent organization unit not found
                  value:
                    code: "OU-1005"
                    message: "Parent organization unit not found"
                    description: "Parent organization unit not found"
                circular-dependency:
                  summary: Circular dependency detected
                  value:
                    code: "OU-1007"
                    message: "Circular dependency detected"
                    description: "Setting this parent would create a circular dependency"
        "404":
          description: Organization unit not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: "OU-1003"
                message: "Organization unit not found"
                description: "The organization unit with the specified id does not exist"
        "409":
          description: Organization unit name conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: "OU-1004"
                message: "Organization unit name conflict"
                description: "An organization unit with the same name exists under the same parent"
        "500":
          description: Internal server error

    delete:
      tags:
        - organization-units
      summary: Delete an organization unit by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Organization unit deleted
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                has-children:
                  summary: Organization unit has children
                  value:
                    code: "OU-1006"
                    message: "Organization unit has children"
                    description: "Cannot delete organization unit with children or users/groups"
        "404":
          description: Organization unit not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: "OU-1003"
                message: "Organization unit not found"
                description: "The organization unit with the specified id does not exist"
        "500":
          description: Internal server error

components:
  schemas:
    OrganizationUnitBasic:
      type: object
      required: [id, name, parent, organizationUnits]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        parent:
          type: string
          format: uuid
          nullable: true
        organizationUnits:
          type: array
          items:
            type: string
            format: uuid

    OrganizationUnit:
      allOf:
        - $ref: '#/components/schemas/OrganizationUnitBasic'
      properties:
        users:
          type: array
          items:
            type: string
            format: uuid
        groups:
          type: array
          items:
            type: string
            format: uuid

    CreateOrganizationUnitRequest:
      type: object
      required: [name, parent]
      properties:
        name:
          type: string
        description:
          type: string
        parent:
          type: string
          format: uuid
          nullable: true

    UpdateOrganizationUnitRequest:
      allOf:
        - $ref: '#/components/schemas/CreateOrganizationUnitRequest'

    Error:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
        message:
          type: string
        description:
          type: string