-- Table to store OAuth2 authorization codes.
CREATE TABLE IDN_OAUTH2_AUTHZ_CODE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CODE_ID VARCHAR(36) UNIQUE NOT NULL,
    AUTHORIZATION_CODE VARCHAR(500) NOT NULL,
    CONSUMER_KEY VARCHAR(255) NOT NULL,
    CALLBACK_URL VARCHAR(500),
    AUTHZ_USER VARCHAR(255) NOT NULL,
    TIME_CREATED DATETIME NOT NULL,
    EXPIRY_TIME DATETIME NOT NULL,
    STATE VARCHAR(50) NOT NULL
);

-- Table to store scopes associated with OAuth2 authorization codes.
CREATE TABLE IDN_OAUTH2_AUTHZ_CODE_SCOPE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CODE_ID VARCHAR(36) NOT NULL REFERENCES IDN_OAUTH2_AUTHZ_CODE(CODE_ID) ON DELETE CASCADE,
    SCOPE VARCHAR(255) NOT NULL,
    UNIQUE (CODE_ID, SCOPE)
);

-- Table to store flow context metadata and state
CREATE TABLE FLOW_CONTEXT (
    FLOW_ID VARCHAR(36) PRIMARY KEY,
    APP_ID VARCHAR(36) NOT NULL,
    CURRENT_NODE_ID VARCHAR(50),
    CURRENT_ACTION_ID VARCHAR(50),
    GRAPH_ID VARCHAR(50) NOT NULL,
    RUNTIME_DATA TEXT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Table to store flow user data
CREATE TABLE FLOW_USER_DATA (
    FLOW_ID VARCHAR(36) PRIMARY KEY,
    IS_AUTHENTICATED BOOLEAN NOT NULL DEFAULT 0,
    USER_ID VARCHAR(36),
    USER_INPUTS TEXT,
    USER_ATTRIBUTES TEXT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FLOW_ID) REFERENCES FLOW_CONTEXT(FLOW_ID) ON DELETE CASCADE
);
