// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oauthmock

import (
	"github.com/asgardeo/thunder/internal/authn/oauth"
	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	"github.com/asgardeo/thunder/internal/user"
	mock "github.com/stretchr/testify/mock"
)

// NewOAuthAuthnServiceInterfaceMock creates a new instance of OAuthAuthnServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOAuthAuthnServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OAuthAuthnServiceInterfaceMock {
	mock := &OAuthAuthnServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OAuthAuthnServiceInterfaceMock is an autogenerated mock type for the OAuthAuthnServiceInterface type
type OAuthAuthnServiceInterfaceMock struct {
	mock.Mock
}

type OAuthAuthnServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OAuthAuthnServiceInterfaceMock) EXPECT() *OAuthAuthnServiceInterfaceMock_Expecter {
	return &OAuthAuthnServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// BuildAuthorizeURL provides a mock function for the type OAuthAuthnServiceInterfaceMock
func (_mock *OAuthAuthnServiceInterfaceMock) BuildAuthorizeURL(idpID string) (string, *serviceerror.ServiceError) {
	ret := _mock.Called(idpID)

	if len(ret) == 0 {
		panic("no return value specified for BuildAuthorizeURL")
	}

	var r0 string
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string) (string, *serviceerror.ServiceError)); ok {
		return returnFunc(idpID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(idpID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(idpID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// OAuthAuthnServiceInterfaceMock_BuildAuthorizeURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildAuthorizeURL'
type OAuthAuthnServiceInterfaceMock_BuildAuthorizeURL_Call struct {
	*mock.Call
}

// BuildAuthorizeURL is a helper method to define mock.On call
//   - idpID string
func (_e *OAuthAuthnServiceInterfaceMock_Expecter) BuildAuthorizeURL(idpID interface{}) *OAuthAuthnServiceInterfaceMock_BuildAuthorizeURL_Call {
	return &OAuthAuthnServiceInterfaceMock_BuildAuthorizeURL_Call{Call: _e.mock.On("BuildAuthorizeURL", idpID)}
}

func (_c *OAuthAuthnServiceInterfaceMock_BuildAuthorizeURL_Call) Run(run func(idpID string)) *OAuthAuthnServiceInterfaceMock_BuildAuthorizeURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OAuthAuthnServiceInterfaceMock_BuildAuthorizeURL_Call) Return(s string, serviceError *serviceerror.ServiceError) *OAuthAuthnServiceInterfaceMock_BuildAuthorizeURL_Call {
	_c.Call.Return(s, serviceError)
	return _c
}

func (_c *OAuthAuthnServiceInterfaceMock_BuildAuthorizeURL_Call) RunAndReturn(run func(idpID string) (string, *serviceerror.ServiceError)) *OAuthAuthnServiceInterfaceMock_BuildAuthorizeURL_Call {
	_c.Call.Return(run)
	return _c
}

// ExchangeCodeForToken provides a mock function for the type OAuthAuthnServiceInterfaceMock
func (_mock *OAuthAuthnServiceInterfaceMock) ExchangeCodeForToken(idpID string, code string, validateResponse bool) (*oauth.TokenResponse, *serviceerror.ServiceError) {
	ret := _mock.Called(idpID, code, validateResponse)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeCodeForToken")
	}

	var r0 *oauth.TokenResponse
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, string, bool) (*oauth.TokenResponse, *serviceerror.ServiceError)); ok {
		return returnFunc(idpID, code, validateResponse)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, bool) *oauth.TokenResponse); ok {
		r0 = returnFunc(idpID, code, validateResponse)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.TokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, bool) *serviceerror.ServiceError); ok {
		r1 = returnFunc(idpID, code, validateResponse)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// OAuthAuthnServiceInterfaceMock_ExchangeCodeForToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeCodeForToken'
type OAuthAuthnServiceInterfaceMock_ExchangeCodeForToken_Call struct {
	*mock.Call
}

// ExchangeCodeForToken is a helper method to define mock.On call
//   - idpID string
//   - code string
//   - validateResponse bool
func (_e *OAuthAuthnServiceInterfaceMock_Expecter) ExchangeCodeForToken(idpID interface{}, code interface{}, validateResponse interface{}) *OAuthAuthnServiceInterfaceMock_ExchangeCodeForToken_Call {
	return &OAuthAuthnServiceInterfaceMock_ExchangeCodeForToken_Call{Call: _e.mock.On("ExchangeCodeForToken", idpID, code, validateResponse)}
}

func (_c *OAuthAuthnServiceInterfaceMock_ExchangeCodeForToken_Call) Run(run func(idpID string, code string, validateResponse bool)) *OAuthAuthnServiceInterfaceMock_ExchangeCodeForToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OAuthAuthnServiceInterfaceMock_ExchangeCodeForToken_Call) Return(tokenResponse *oauth.TokenResponse, serviceError *serviceerror.ServiceError) *OAuthAuthnServiceInterfaceMock_ExchangeCodeForToken_Call {
	_c.Call.Return(tokenResponse, serviceError)
	return _c
}

func (_c *OAuthAuthnServiceInterfaceMock_ExchangeCodeForToken_Call) RunAndReturn(run func(idpID string, code string, validateResponse bool) (*oauth.TokenResponse, *serviceerror.ServiceError)) *OAuthAuthnServiceInterfaceMock_ExchangeCodeForToken_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUserInfo provides a mock function for the type OAuthAuthnServiceInterfaceMock
func (_mock *OAuthAuthnServiceInterfaceMock) FetchUserInfo(idpID string, accessToken string) (map[string]interface{}, *serviceerror.ServiceError) {
	ret := _mock.Called(idpID, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for FetchUserInfo")
	}

	var r0 map[string]interface{}
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, string) (map[string]interface{}, *serviceerror.ServiceError)); ok {
		return returnFunc(idpID, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) map[string]interface{}); ok {
		r0 = returnFunc(idpID, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(idpID, accessToken)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// OAuthAuthnServiceInterfaceMock_FetchUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUserInfo'
type OAuthAuthnServiceInterfaceMock_FetchUserInfo_Call struct {
	*mock.Call
}

// FetchUserInfo is a helper method to define mock.On call
//   - idpID string
//   - accessToken string
func (_e *OAuthAuthnServiceInterfaceMock_Expecter) FetchUserInfo(idpID interface{}, accessToken interface{}) *OAuthAuthnServiceInterfaceMock_FetchUserInfo_Call {
	return &OAuthAuthnServiceInterfaceMock_FetchUserInfo_Call{Call: _e.mock.On("FetchUserInfo", idpID, accessToken)}
}

func (_c *OAuthAuthnServiceInterfaceMock_FetchUserInfo_Call) Run(run func(idpID string, accessToken string)) *OAuthAuthnServiceInterfaceMock_FetchUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OAuthAuthnServiceInterfaceMock_FetchUserInfo_Call) Return(stringToIfaceVal map[string]interface{}, serviceError *serviceerror.ServiceError) *OAuthAuthnServiceInterfaceMock_FetchUserInfo_Call {
	_c.Call.Return(stringToIfaceVal, serviceError)
	return _c
}

func (_c *OAuthAuthnServiceInterfaceMock_FetchUserInfo_Call) RunAndReturn(run func(idpID string, accessToken string) (map[string]interface{}, *serviceerror.ServiceError)) *OAuthAuthnServiceInterfaceMock_FetchUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUserInfoWithClientConfig provides a mock function for the type OAuthAuthnServiceInterfaceMock
func (_mock *OAuthAuthnServiceInterfaceMock) FetchUserInfoWithClientConfig(oAuthClientConfig *oauth.OAuthClientConfig, accessToken string) (map[string]interface{}, *serviceerror.ServiceError) {
	ret := _mock.Called(oAuthClientConfig, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for FetchUserInfoWithClientConfig")
	}

	var r0 map[string]interface{}
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(*oauth.OAuthClientConfig, string) (map[string]interface{}, *serviceerror.ServiceError)); ok {
		return returnFunc(oAuthClientConfig, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(*oauth.OAuthClientConfig, string) map[string]interface{}); ok {
		r0 = returnFunc(oAuthClientConfig, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*oauth.OAuthClientConfig, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(oAuthClientConfig, accessToken)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// OAuthAuthnServiceInterfaceMock_FetchUserInfoWithClientConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUserInfoWithClientConfig'
type OAuthAuthnServiceInterfaceMock_FetchUserInfoWithClientConfig_Call struct {
	*mock.Call
}

// FetchUserInfoWithClientConfig is a helper method to define mock.On call
//   - oAuthClientConfig *oauth.OAuthClientConfig
//   - accessToken string
func (_e *OAuthAuthnServiceInterfaceMock_Expecter) FetchUserInfoWithClientConfig(oAuthClientConfig interface{}, accessToken interface{}) *OAuthAuthnServiceInterfaceMock_FetchUserInfoWithClientConfig_Call {
	return &OAuthAuthnServiceInterfaceMock_FetchUserInfoWithClientConfig_Call{Call: _e.mock.On("FetchUserInfoWithClientConfig", oAuthClientConfig, accessToken)}
}

func (_c *OAuthAuthnServiceInterfaceMock_FetchUserInfoWithClientConfig_Call) Run(run func(oAuthClientConfig *oauth.OAuthClientConfig, accessToken string)) *OAuthAuthnServiceInterfaceMock_FetchUserInfoWithClientConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *oauth.OAuthClientConfig
		if args[0] != nil {
			arg0 = args[0].(*oauth.OAuthClientConfig)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OAuthAuthnServiceInterfaceMock_FetchUserInfoWithClientConfig_Call) Return(stringToIfaceVal map[string]interface{}, serviceError *serviceerror.ServiceError) *OAuthAuthnServiceInterfaceMock_FetchUserInfoWithClientConfig_Call {
	_c.Call.Return(stringToIfaceVal, serviceError)
	return _c
}

func (_c *OAuthAuthnServiceInterfaceMock_FetchUserInfoWithClientConfig_Call) RunAndReturn(run func(oAuthClientConfig *oauth.OAuthClientConfig, accessToken string) (map[string]interface{}, *serviceerror.ServiceError)) *OAuthAuthnServiceInterfaceMock_FetchUserInfoWithClientConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetInternalUser provides a mock function for the type OAuthAuthnServiceInterfaceMock
func (_mock *OAuthAuthnServiceInterfaceMock) GetInternalUser(sub string) (*user.User, *serviceerror.ServiceError) {
	ret := _mock.Called(sub)

	if len(ret) == 0 {
		panic("no return value specified for GetInternalUser")
	}

	var r0 *user.User
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string) (*user.User, *serviceerror.ServiceError)); ok {
		return returnFunc(sub)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *user.User); ok {
		r0 = returnFunc(sub)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(sub)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// OAuthAuthnServiceInterfaceMock_GetInternalUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInternalUser'
type OAuthAuthnServiceInterfaceMock_GetInternalUser_Call struct {
	*mock.Call
}

// GetInternalUser is a helper method to define mock.On call
//   - sub string
func (_e *OAuthAuthnServiceInterfaceMock_Expecter) GetInternalUser(sub interface{}) *OAuthAuthnServiceInterfaceMock_GetInternalUser_Call {
	return &OAuthAuthnServiceInterfaceMock_GetInternalUser_Call{Call: _e.mock.On("GetInternalUser", sub)}
}

func (_c *OAuthAuthnServiceInterfaceMock_GetInternalUser_Call) Run(run func(sub string)) *OAuthAuthnServiceInterfaceMock_GetInternalUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OAuthAuthnServiceInterfaceMock_GetInternalUser_Call) Return(user1 *user.User, serviceError *serviceerror.ServiceError) *OAuthAuthnServiceInterfaceMock_GetInternalUser_Call {
	_c.Call.Return(user1, serviceError)
	return _c
}

func (_c *OAuthAuthnServiceInterfaceMock_GetInternalUser_Call) RunAndReturn(run func(sub string) (*user.User, *serviceerror.ServiceError)) *OAuthAuthnServiceInterfaceMock_GetInternalUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetOAuthClientConfig provides a mock function for the type OAuthAuthnServiceInterfaceMock
func (_mock *OAuthAuthnServiceInterfaceMock) GetOAuthClientConfig(idpID string) (*oauth.OAuthClientConfig, *serviceerror.ServiceError) {
	ret := _mock.Called(idpID)

	if len(ret) == 0 {
		panic("no return value specified for GetOAuthClientConfig")
	}

	var r0 *oauth.OAuthClientConfig
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string) (*oauth.OAuthClientConfig, *serviceerror.ServiceError)); ok {
		return returnFunc(idpID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *oauth.OAuthClientConfig); ok {
		r0 = returnFunc(idpID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.OAuthClientConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(idpID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// OAuthAuthnServiceInterfaceMock_GetOAuthClientConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOAuthClientConfig'
type OAuthAuthnServiceInterfaceMock_GetOAuthClientConfig_Call struct {
	*mock.Call
}

// GetOAuthClientConfig is a helper method to define mock.On call
//   - idpID string
func (_e *OAuthAuthnServiceInterfaceMock_Expecter) GetOAuthClientConfig(idpID interface{}) *OAuthAuthnServiceInterfaceMock_GetOAuthClientConfig_Call {
	return &OAuthAuthnServiceInterfaceMock_GetOAuthClientConfig_Call{Call: _e.mock.On("GetOAuthClientConfig", idpID)}
}

func (_c *OAuthAuthnServiceInterfaceMock_GetOAuthClientConfig_Call) Run(run func(idpID string)) *OAuthAuthnServiceInterfaceMock_GetOAuthClientConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OAuthAuthnServiceInterfaceMock_GetOAuthClientConfig_Call) Return(oAuthClientConfig *oauth.OAuthClientConfig, serviceError *serviceerror.ServiceError) *OAuthAuthnServiceInterfaceMock_GetOAuthClientConfig_Call {
	_c.Call.Return(oAuthClientConfig, serviceError)
	return _c
}

func (_c *OAuthAuthnServiceInterfaceMock_GetOAuthClientConfig_Call) RunAndReturn(run func(idpID string) (*oauth.OAuthClientConfig, *serviceerror.ServiceError)) *OAuthAuthnServiceInterfaceMock_GetOAuthClientConfig_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateTokenResponse provides a mock function for the type OAuthAuthnServiceInterfaceMock
func (_mock *OAuthAuthnServiceInterfaceMock) ValidateTokenResponse(idpID string, tokenResp *oauth.TokenResponse) *serviceerror.ServiceError {
	ret := _mock.Called(idpID, tokenResp)

	if len(ret) == 0 {
		panic("no return value specified for ValidateTokenResponse")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, *oauth.TokenResponse) *serviceerror.ServiceError); ok {
		r0 = returnFunc(idpID, tokenResp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// OAuthAuthnServiceInterfaceMock_ValidateTokenResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateTokenResponse'
type OAuthAuthnServiceInterfaceMock_ValidateTokenResponse_Call struct {
	*mock.Call
}

// ValidateTokenResponse is a helper method to define mock.On call
//   - idpID string
//   - tokenResp *oauth.TokenResponse
func (_e *OAuthAuthnServiceInterfaceMock_Expecter) ValidateTokenResponse(idpID interface{}, tokenResp interface{}) *OAuthAuthnServiceInterfaceMock_ValidateTokenResponse_Call {
	return &OAuthAuthnServiceInterfaceMock_ValidateTokenResponse_Call{Call: _e.mock.On("ValidateTokenResponse", idpID, tokenResp)}
}

func (_c *OAuthAuthnServiceInterfaceMock_ValidateTokenResponse_Call) Run(run func(idpID string, tokenResp *oauth.TokenResponse)) *OAuthAuthnServiceInterfaceMock_ValidateTokenResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *oauth.TokenResponse
		if args[1] != nil {
			arg1 = args[1].(*oauth.TokenResponse)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OAuthAuthnServiceInterfaceMock_ValidateTokenResponse_Call) Return(serviceError *serviceerror.ServiceError) *OAuthAuthnServiceInterfaceMock_ValidateTokenResponse_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *OAuthAuthnServiceInterfaceMock_ValidateTokenResponse_Call) RunAndReturn(run func(idpID string, tokenResp *oauth.TokenResponse) *serviceerror.ServiceError) *OAuthAuthnServiceInterfaceMock_ValidateTokenResponse_Call {
	_c.Call.Return(run)
	return _c
}
