// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oidcmock

import (
	"github.com/asgardeo/thunder/internal/authn/oauth"
	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	"github.com/asgardeo/thunder/internal/user"
	mock "github.com/stretchr/testify/mock"
)

// NewOIDCAuthnCoreServiceInterfaceMock creates a new instance of OIDCAuthnCoreServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOIDCAuthnCoreServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OIDCAuthnCoreServiceInterfaceMock {
	mock := &OIDCAuthnCoreServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OIDCAuthnCoreServiceInterfaceMock is an autogenerated mock type for the OIDCAuthnCoreServiceInterface type
type OIDCAuthnCoreServiceInterfaceMock struct {
	mock.Mock
}

type OIDCAuthnCoreServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OIDCAuthnCoreServiceInterfaceMock) EXPECT() *OIDCAuthnCoreServiceInterfaceMock_Expecter {
	return &OIDCAuthnCoreServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// BuildAuthorizeURL provides a mock function for the type OIDCAuthnCoreServiceInterfaceMock
func (_mock *OIDCAuthnCoreServiceInterfaceMock) BuildAuthorizeURL(idpID string) (string, *serviceerror.ServiceError) {
	ret := _mock.Called(idpID)

	if len(ret) == 0 {
		panic("no return value specified for BuildAuthorizeURL")
	}

	var r0 string
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string) (string, *serviceerror.ServiceError)); ok {
		return returnFunc(idpID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(idpID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(idpID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// OIDCAuthnCoreServiceInterfaceMock_BuildAuthorizeURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildAuthorizeURL'
type OIDCAuthnCoreServiceInterfaceMock_BuildAuthorizeURL_Call struct {
	*mock.Call
}

// BuildAuthorizeURL is a helper method to define mock.On call
//   - idpID string
func (_e *OIDCAuthnCoreServiceInterfaceMock_Expecter) BuildAuthorizeURL(idpID interface{}) *OIDCAuthnCoreServiceInterfaceMock_BuildAuthorizeURL_Call {
	return &OIDCAuthnCoreServiceInterfaceMock_BuildAuthorizeURL_Call{Call: _e.mock.On("BuildAuthorizeURL", idpID)}
}

func (_c *OIDCAuthnCoreServiceInterfaceMock_BuildAuthorizeURL_Call) Run(run func(idpID string)) *OIDCAuthnCoreServiceInterfaceMock_BuildAuthorizeURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OIDCAuthnCoreServiceInterfaceMock_BuildAuthorizeURL_Call) Return(s string, serviceError *serviceerror.ServiceError) *OIDCAuthnCoreServiceInterfaceMock_BuildAuthorizeURL_Call {
	_c.Call.Return(s, serviceError)
	return _c
}

func (_c *OIDCAuthnCoreServiceInterfaceMock_BuildAuthorizeURL_Call) RunAndReturn(run func(idpID string) (string, *serviceerror.ServiceError)) *OIDCAuthnCoreServiceInterfaceMock_BuildAuthorizeURL_Call {
	_c.Call.Return(run)
	return _c
}

// ExchangeCodeForToken provides a mock function for the type OIDCAuthnCoreServiceInterfaceMock
func (_mock *OIDCAuthnCoreServiceInterfaceMock) ExchangeCodeForToken(idpID string, code string, validateResponse bool) (*oauth.TokenResponse, *serviceerror.ServiceError) {
	ret := _mock.Called(idpID, code, validateResponse)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeCodeForToken")
	}

	var r0 *oauth.TokenResponse
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, string, bool) (*oauth.TokenResponse, *serviceerror.ServiceError)); ok {
		return returnFunc(idpID, code, validateResponse)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, bool) *oauth.TokenResponse); ok {
		r0 = returnFunc(idpID, code, validateResponse)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.TokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, bool) *serviceerror.ServiceError); ok {
		r1 = returnFunc(idpID, code, validateResponse)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// OIDCAuthnCoreServiceInterfaceMock_ExchangeCodeForToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeCodeForToken'
type OIDCAuthnCoreServiceInterfaceMock_ExchangeCodeForToken_Call struct {
	*mock.Call
}

// ExchangeCodeForToken is a helper method to define mock.On call
//   - idpID string
//   - code string
//   - validateResponse bool
func (_e *OIDCAuthnCoreServiceInterfaceMock_Expecter) ExchangeCodeForToken(idpID interface{}, code interface{}, validateResponse interface{}) *OIDCAuthnCoreServiceInterfaceMock_ExchangeCodeForToken_Call {
	return &OIDCAuthnCoreServiceInterfaceMock_ExchangeCodeForToken_Call{Call: _e.mock.On("ExchangeCodeForToken", idpID, code, validateResponse)}
}

func (_c *OIDCAuthnCoreServiceInterfaceMock_ExchangeCodeForToken_Call) Run(run func(idpID string, code string, validateResponse bool)) *OIDCAuthnCoreServiceInterfaceMock_ExchangeCodeForToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OIDCAuthnCoreServiceInterfaceMock_ExchangeCodeForToken_Call) Return(tokenResponse *oauth.TokenResponse, serviceError *serviceerror.ServiceError) *OIDCAuthnCoreServiceInterfaceMock_ExchangeCodeForToken_Call {
	_c.Call.Return(tokenResponse, serviceError)
	return _c
}

func (_c *OIDCAuthnCoreServiceInterfaceMock_ExchangeCodeForToken_Call) RunAndReturn(run func(idpID string, code string, validateResponse bool) (*oauth.TokenResponse, *serviceerror.ServiceError)) *OIDCAuthnCoreServiceInterfaceMock_ExchangeCodeForToken_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUserInfo provides a mock function for the type OIDCAuthnCoreServiceInterfaceMock
func (_mock *OIDCAuthnCoreServiceInterfaceMock) FetchUserInfo(idpID string, accessToken string) (map[string]interface{}, *serviceerror.ServiceError) {
	ret := _mock.Called(idpID, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for FetchUserInfo")
	}

	var r0 map[string]interface{}
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, string) (map[string]interface{}, *serviceerror.ServiceError)); ok {
		return returnFunc(idpID, accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) map[string]interface{}); ok {
		r0 = returnFunc(idpID, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(idpID, accessToken)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// OIDCAuthnCoreServiceInterfaceMock_FetchUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUserInfo'
type OIDCAuthnCoreServiceInterfaceMock_FetchUserInfo_Call struct {
	*mock.Call
}

// FetchUserInfo is a helper method to define mock.On call
//   - idpID string
//   - accessToken string
func (_e *OIDCAuthnCoreServiceInterfaceMock_Expecter) FetchUserInfo(idpID interface{}, accessToken interface{}) *OIDCAuthnCoreServiceInterfaceMock_FetchUserInfo_Call {
	return &OIDCAuthnCoreServiceInterfaceMock_FetchUserInfo_Call{Call: _e.mock.On("FetchUserInfo", idpID, accessToken)}
}

func (_c *OIDCAuthnCoreServiceInterfaceMock_FetchUserInfo_Call) Run(run func(idpID string, accessToken string)) *OIDCAuthnCoreServiceInterfaceMock_FetchUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OIDCAuthnCoreServiceInterfaceMock_FetchUserInfo_Call) Return(stringToIfaceVal map[string]interface{}, serviceError *serviceerror.ServiceError) *OIDCAuthnCoreServiceInterfaceMock_FetchUserInfo_Call {
	_c.Call.Return(stringToIfaceVal, serviceError)
	return _c
}

func (_c *OIDCAuthnCoreServiceInterfaceMock_FetchUserInfo_Call) RunAndReturn(run func(idpID string, accessToken string) (map[string]interface{}, *serviceerror.ServiceError)) *OIDCAuthnCoreServiceInterfaceMock_FetchUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetIDTokenClaims provides a mock function for the type OIDCAuthnCoreServiceInterfaceMock
func (_mock *OIDCAuthnCoreServiceInterfaceMock) GetIDTokenClaims(idToken string) (map[string]interface{}, *serviceerror.ServiceError) {
	ret := _mock.Called(idToken)

	if len(ret) == 0 {
		panic("no return value specified for GetIDTokenClaims")
	}

	var r0 map[string]interface{}
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string) (map[string]interface{}, *serviceerror.ServiceError)); ok {
		return returnFunc(idToken)
	}
	if returnFunc, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = returnFunc(idToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(idToken)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// OIDCAuthnCoreServiceInterfaceMock_GetIDTokenClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIDTokenClaims'
type OIDCAuthnCoreServiceInterfaceMock_GetIDTokenClaims_Call struct {
	*mock.Call
}

// GetIDTokenClaims is a helper method to define mock.On call
//   - idToken string
func (_e *OIDCAuthnCoreServiceInterfaceMock_Expecter) GetIDTokenClaims(idToken interface{}) *OIDCAuthnCoreServiceInterfaceMock_GetIDTokenClaims_Call {
	return &OIDCAuthnCoreServiceInterfaceMock_GetIDTokenClaims_Call{Call: _e.mock.On("GetIDTokenClaims", idToken)}
}

func (_c *OIDCAuthnCoreServiceInterfaceMock_GetIDTokenClaims_Call) Run(run func(idToken string)) *OIDCAuthnCoreServiceInterfaceMock_GetIDTokenClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OIDCAuthnCoreServiceInterfaceMock_GetIDTokenClaims_Call) Return(stringToIfaceVal map[string]interface{}, serviceError *serviceerror.ServiceError) *OIDCAuthnCoreServiceInterfaceMock_GetIDTokenClaims_Call {
	_c.Call.Return(stringToIfaceVal, serviceError)
	return _c
}

func (_c *OIDCAuthnCoreServiceInterfaceMock_GetIDTokenClaims_Call) RunAndReturn(run func(idToken string) (map[string]interface{}, *serviceerror.ServiceError)) *OIDCAuthnCoreServiceInterfaceMock_GetIDTokenClaims_Call {
	_c.Call.Return(run)
	return _c
}

// GetInternalUser provides a mock function for the type OIDCAuthnCoreServiceInterfaceMock
func (_mock *OIDCAuthnCoreServiceInterfaceMock) GetInternalUser(sub string) (*user.User, *serviceerror.ServiceError) {
	ret := _mock.Called(sub)

	if len(ret) == 0 {
		panic("no return value specified for GetInternalUser")
	}

	var r0 *user.User
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string) (*user.User, *serviceerror.ServiceError)); ok {
		return returnFunc(sub)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *user.User); ok {
		r0 = returnFunc(sub)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(sub)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// OIDCAuthnCoreServiceInterfaceMock_GetInternalUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInternalUser'
type OIDCAuthnCoreServiceInterfaceMock_GetInternalUser_Call struct {
	*mock.Call
}

// GetInternalUser is a helper method to define mock.On call
//   - sub string
func (_e *OIDCAuthnCoreServiceInterfaceMock_Expecter) GetInternalUser(sub interface{}) *OIDCAuthnCoreServiceInterfaceMock_GetInternalUser_Call {
	return &OIDCAuthnCoreServiceInterfaceMock_GetInternalUser_Call{Call: _e.mock.On("GetInternalUser", sub)}
}

func (_c *OIDCAuthnCoreServiceInterfaceMock_GetInternalUser_Call) Run(run func(sub string)) *OIDCAuthnCoreServiceInterfaceMock_GetInternalUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OIDCAuthnCoreServiceInterfaceMock_GetInternalUser_Call) Return(user1 *user.User, serviceError *serviceerror.ServiceError) *OIDCAuthnCoreServiceInterfaceMock_GetInternalUser_Call {
	_c.Call.Return(user1, serviceError)
	return _c
}

func (_c *OIDCAuthnCoreServiceInterfaceMock_GetInternalUser_Call) RunAndReturn(run func(sub string) (*user.User, *serviceerror.ServiceError)) *OIDCAuthnCoreServiceInterfaceMock_GetInternalUser_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateIDToken provides a mock function for the type OIDCAuthnCoreServiceInterfaceMock
func (_mock *OIDCAuthnCoreServiceInterfaceMock) ValidateIDToken(idpID string, idToken string) *serviceerror.ServiceError {
	ret := _mock.Called(idpID, idToken)

	if len(ret) == 0 {
		panic("no return value specified for ValidateIDToken")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string, string) *serviceerror.ServiceError); ok {
		r0 = returnFunc(idpID, idToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// OIDCAuthnCoreServiceInterfaceMock_ValidateIDToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateIDToken'
type OIDCAuthnCoreServiceInterfaceMock_ValidateIDToken_Call struct {
	*mock.Call
}

// ValidateIDToken is a helper method to define mock.On call
//   - idpID string
//   - idToken string
func (_e *OIDCAuthnCoreServiceInterfaceMock_Expecter) ValidateIDToken(idpID interface{}, idToken interface{}) *OIDCAuthnCoreServiceInterfaceMock_ValidateIDToken_Call {
	return &OIDCAuthnCoreServiceInterfaceMock_ValidateIDToken_Call{Call: _e.mock.On("ValidateIDToken", idpID, idToken)}
}

func (_c *OIDCAuthnCoreServiceInterfaceMock_ValidateIDToken_Call) Run(run func(idpID string, idToken string)) *OIDCAuthnCoreServiceInterfaceMock_ValidateIDToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OIDCAuthnCoreServiceInterfaceMock_ValidateIDToken_Call) Return(serviceError *serviceerror.ServiceError) *OIDCAuthnCoreServiceInterfaceMock_ValidateIDToken_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *OIDCAuthnCoreServiceInterfaceMock_ValidateIDToken_Call) RunAndReturn(run func(idpID string, idToken string) *serviceerror.ServiceError) *OIDCAuthnCoreServiceInterfaceMock_ValidateIDToken_Call {
	_c.Call.Return(run)
	return _c
}
