// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package granthandlersmock

import (
	model0 "github.com/asgardeo/thunder/internal/application/model"
	"github.com/asgardeo/thunder/internal/oauth/oauth2/model"
	mock "github.com/stretchr/testify/mock"
)

// NewRefreshTokenGrantHandlerInterfaceMock creates a new instance of RefreshTokenGrantHandlerInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenGrantHandlerInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenGrantHandlerInterfaceMock {
	mock := &RefreshTokenGrantHandlerInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RefreshTokenGrantHandlerInterfaceMock is an autogenerated mock type for the RefreshTokenGrantHandlerInterface type
type RefreshTokenGrantHandlerInterfaceMock struct {
	mock.Mock
}

type RefreshTokenGrantHandlerInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshTokenGrantHandlerInterfaceMock) EXPECT() *RefreshTokenGrantHandlerInterfaceMock_Expecter {
	return &RefreshTokenGrantHandlerInterfaceMock_Expecter{mock: &_m.Mock}
}

// HandleGrant provides a mock function for the type RefreshTokenGrantHandlerInterfaceMock
func (_mock *RefreshTokenGrantHandlerInterfaceMock) HandleGrant(tokenRequest *model.TokenRequest, oauthApp *model0.OAuthAppConfigProcessedDTO, ctx *model.TokenContext) (*model.TokenResponseDTO, *model.ErrorResponse) {
	ret := _mock.Called(tokenRequest, oauthApp, ctx)

	if len(ret) == 0 {
		panic("no return value specified for HandleGrant")
	}

	var r0 *model.TokenResponseDTO
	var r1 *model.ErrorResponse
	if returnFunc, ok := ret.Get(0).(func(*model.TokenRequest, *model0.OAuthAppConfigProcessedDTO, *model.TokenContext) (*model.TokenResponseDTO, *model.ErrorResponse)); ok {
		return returnFunc(tokenRequest, oauthApp, ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.TokenRequest, *model0.OAuthAppConfigProcessedDTO, *model.TokenContext) *model.TokenResponseDTO); ok {
		r0 = returnFunc(tokenRequest, oauthApp, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TokenResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.TokenRequest, *model0.OAuthAppConfigProcessedDTO, *model.TokenContext) *model.ErrorResponse); ok {
		r1 = returnFunc(tokenRequest, oauthApp, ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.ErrorResponse)
		}
	}
	return r0, r1
}

// RefreshTokenGrantHandlerInterfaceMock_HandleGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleGrant'
type RefreshTokenGrantHandlerInterfaceMock_HandleGrant_Call struct {
	*mock.Call
}

// HandleGrant is a helper method to define mock.On call
//   - tokenRequest *model.TokenRequest
//   - oauthApp *model0.OAuthAppConfigProcessedDTO
//   - ctx *model.TokenContext
func (_e *RefreshTokenGrantHandlerInterfaceMock_Expecter) HandleGrant(tokenRequest interface{}, oauthApp interface{}, ctx interface{}) *RefreshTokenGrantHandlerInterfaceMock_HandleGrant_Call {
	return &RefreshTokenGrantHandlerInterfaceMock_HandleGrant_Call{Call: _e.mock.On("HandleGrant", tokenRequest, oauthApp, ctx)}
}

func (_c *RefreshTokenGrantHandlerInterfaceMock_HandleGrant_Call) Run(run func(tokenRequest *model.TokenRequest, oauthApp *model0.OAuthAppConfigProcessedDTO, ctx *model.TokenContext)) *RefreshTokenGrantHandlerInterfaceMock_HandleGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.TokenRequest
		if args[0] != nil {
			arg0 = args[0].(*model.TokenRequest)
		}
		var arg1 *model0.OAuthAppConfigProcessedDTO
		if args[1] != nil {
			arg1 = args[1].(*model0.OAuthAppConfigProcessedDTO)
		}
		var arg2 *model.TokenContext
		if args[2] != nil {
			arg2 = args[2].(*model.TokenContext)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RefreshTokenGrantHandlerInterfaceMock_HandleGrant_Call) Return(tokenResponseDTO *model.TokenResponseDTO, errorResponse *model.ErrorResponse) *RefreshTokenGrantHandlerInterfaceMock_HandleGrant_Call {
	_c.Call.Return(tokenResponseDTO, errorResponse)
	return _c
}

func (_c *RefreshTokenGrantHandlerInterfaceMock_HandleGrant_Call) RunAndReturn(run func(tokenRequest *model.TokenRequest, oauthApp *model0.OAuthAppConfigProcessedDTO, ctx *model.TokenContext) (*model.TokenResponseDTO, *model.ErrorResponse)) *RefreshTokenGrantHandlerInterfaceMock_HandleGrant_Call {
	_c.Call.Return(run)
	return _c
}

// IssueRefreshToken provides a mock function for the type RefreshTokenGrantHandlerInterfaceMock
func (_mock *RefreshTokenGrantHandlerInterfaceMock) IssueRefreshToken(tokenResponse *model.TokenResponseDTO, ctx *model.TokenContext, clientID string, grantType string, scopes []string) *model.ErrorResponse {
	ret := _mock.Called(tokenResponse, ctx, clientID, grantType, scopes)

	if len(ret) == 0 {
		panic("no return value specified for IssueRefreshToken")
	}

	var r0 *model.ErrorResponse
	if returnFunc, ok := ret.Get(0).(func(*model.TokenResponseDTO, *model.TokenContext, string, string, []string) *model.ErrorResponse); ok {
		r0 = returnFunc(tokenResponse, ctx, clientID, grantType, scopes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ErrorResponse)
		}
	}
	return r0
}

// RefreshTokenGrantHandlerInterfaceMock_IssueRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueRefreshToken'
type RefreshTokenGrantHandlerInterfaceMock_IssueRefreshToken_Call struct {
	*mock.Call
}

// IssueRefreshToken is a helper method to define mock.On call
//   - tokenResponse *model.TokenResponseDTO
//   - ctx *model.TokenContext
//   - clientID string
//   - grantType string
//   - scopes []string
func (_e *RefreshTokenGrantHandlerInterfaceMock_Expecter) IssueRefreshToken(tokenResponse interface{}, ctx interface{}, clientID interface{}, grantType interface{}, scopes interface{}) *RefreshTokenGrantHandlerInterfaceMock_IssueRefreshToken_Call {
	return &RefreshTokenGrantHandlerInterfaceMock_IssueRefreshToken_Call{Call: _e.mock.On("IssueRefreshToken", tokenResponse, ctx, clientID, grantType, scopes)}
}

func (_c *RefreshTokenGrantHandlerInterfaceMock_IssueRefreshToken_Call) Run(run func(tokenResponse *model.TokenResponseDTO, ctx *model.TokenContext, clientID string, grantType string, scopes []string)) *RefreshTokenGrantHandlerInterfaceMock_IssueRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.TokenResponseDTO
		if args[0] != nil {
			arg0 = args[0].(*model.TokenResponseDTO)
		}
		var arg1 *model.TokenContext
		if args[1] != nil {
			arg1 = args[1].(*model.TokenContext)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *RefreshTokenGrantHandlerInterfaceMock_IssueRefreshToken_Call) Return(errorResponse *model.ErrorResponse) *RefreshTokenGrantHandlerInterfaceMock_IssueRefreshToken_Call {
	_c.Call.Return(errorResponse)
	return _c
}

func (_c *RefreshTokenGrantHandlerInterfaceMock_IssueRefreshToken_Call) RunAndReturn(run func(tokenResponse *model.TokenResponseDTO, ctx *model.TokenContext, clientID string, grantType string, scopes []string) *model.ErrorResponse) *RefreshTokenGrantHandlerInterfaceMock_IssueRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateGrant provides a mock function for the type RefreshTokenGrantHandlerInterfaceMock
func (_mock *RefreshTokenGrantHandlerInterfaceMock) ValidateGrant(tokenRequest *model.TokenRequest, oauthApp *model0.OAuthAppConfigProcessedDTO) *model.ErrorResponse {
	ret := _mock.Called(tokenRequest, oauthApp)

	if len(ret) == 0 {
		panic("no return value specified for ValidateGrant")
	}

	var r0 *model.ErrorResponse
	if returnFunc, ok := ret.Get(0).(func(*model.TokenRequest, *model0.OAuthAppConfigProcessedDTO) *model.ErrorResponse); ok {
		r0 = returnFunc(tokenRequest, oauthApp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ErrorResponse)
		}
	}
	return r0
}

// RefreshTokenGrantHandlerInterfaceMock_ValidateGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateGrant'
type RefreshTokenGrantHandlerInterfaceMock_ValidateGrant_Call struct {
	*mock.Call
}

// ValidateGrant is a helper method to define mock.On call
//   - tokenRequest *model.TokenRequest
//   - oauthApp *model0.OAuthAppConfigProcessedDTO
func (_e *RefreshTokenGrantHandlerInterfaceMock_Expecter) ValidateGrant(tokenRequest interface{}, oauthApp interface{}) *RefreshTokenGrantHandlerInterfaceMock_ValidateGrant_Call {
	return &RefreshTokenGrantHandlerInterfaceMock_ValidateGrant_Call{Call: _e.mock.On("ValidateGrant", tokenRequest, oauthApp)}
}

func (_c *RefreshTokenGrantHandlerInterfaceMock_ValidateGrant_Call) Run(run func(tokenRequest *model.TokenRequest, oauthApp *model0.OAuthAppConfigProcessedDTO)) *RefreshTokenGrantHandlerInterfaceMock_ValidateGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.TokenRequest
		if args[0] != nil {
			arg0 = args[0].(*model.TokenRequest)
		}
		var arg1 *model0.OAuthAppConfigProcessedDTO
		if args[1] != nil {
			arg1 = args[1].(*model0.OAuthAppConfigProcessedDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RefreshTokenGrantHandlerInterfaceMock_ValidateGrant_Call) Return(errorResponse *model.ErrorResponse) *RefreshTokenGrantHandlerInterfaceMock_ValidateGrant_Call {
	_c.Call.Return(errorResponse)
	return _c
}

func (_c *RefreshTokenGrantHandlerInterfaceMock_ValidateGrant_Call) RunAndReturn(run func(tokenRequest *model.TokenRequest, oauthApp *model0.OAuthAppConfigProcessedDTO) *model.ErrorResponse) *RefreshTokenGrantHandlerInterfaceMock_ValidateGrant_Call {
	_c.Call.Return(run)
	return _c
}
