// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authzmock

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewAuthorizeHandlerInterfaceMock creates a new instance of AuthorizeHandlerInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizeHandlerInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorizeHandlerInterfaceMock {
	mock := &AuthorizeHandlerInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthorizeHandlerInterfaceMock is an autogenerated mock type for the AuthorizeHandlerInterface type
type AuthorizeHandlerInterfaceMock struct {
	mock.Mock
}

type AuthorizeHandlerInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthorizeHandlerInterfaceMock) EXPECT() *AuthorizeHandlerInterfaceMock_Expecter {
	return &AuthorizeHandlerInterfaceMock_Expecter{mock: &_m.Mock}
}

// HandleAuthorizeGetRequest provides a mock function for the type AuthorizeHandlerInterfaceMock
func (_mock *AuthorizeHandlerInterfaceMock) HandleAuthorizeGetRequest(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// AuthorizeHandlerInterfaceMock_HandleAuthorizeGetRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleAuthorizeGetRequest'
type AuthorizeHandlerInterfaceMock_HandleAuthorizeGetRequest_Call struct {
	*mock.Call
}

// HandleAuthorizeGetRequest is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AuthorizeHandlerInterfaceMock_Expecter) HandleAuthorizeGetRequest(w interface{}, r interface{}) *AuthorizeHandlerInterfaceMock_HandleAuthorizeGetRequest_Call {
	return &AuthorizeHandlerInterfaceMock_HandleAuthorizeGetRequest_Call{Call: _e.mock.On("HandleAuthorizeGetRequest", w, r)}
}

func (_c *AuthorizeHandlerInterfaceMock_HandleAuthorizeGetRequest_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AuthorizeHandlerInterfaceMock_HandleAuthorizeGetRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthorizeHandlerInterfaceMock_HandleAuthorizeGetRequest_Call) Return() *AuthorizeHandlerInterfaceMock_HandleAuthorizeGetRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthorizeHandlerInterfaceMock_HandleAuthorizeGetRequest_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *AuthorizeHandlerInterfaceMock_HandleAuthorizeGetRequest_Call {
	_c.Run(run)
	return _c
}

// HandleAuthorizePostRequest provides a mock function for the type AuthorizeHandlerInterfaceMock
func (_mock *AuthorizeHandlerInterfaceMock) HandleAuthorizePostRequest(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// AuthorizeHandlerInterfaceMock_HandleAuthorizePostRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleAuthorizePostRequest'
type AuthorizeHandlerInterfaceMock_HandleAuthorizePostRequest_Call struct {
	*mock.Call
}

// HandleAuthorizePostRequest is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AuthorizeHandlerInterfaceMock_Expecter) HandleAuthorizePostRequest(w interface{}, r interface{}) *AuthorizeHandlerInterfaceMock_HandleAuthorizePostRequest_Call {
	return &AuthorizeHandlerInterfaceMock_HandleAuthorizePostRequest_Call{Call: _e.mock.On("HandleAuthorizePostRequest", w, r)}
}

func (_c *AuthorizeHandlerInterfaceMock_HandleAuthorizePostRequest_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AuthorizeHandlerInterfaceMock_HandleAuthorizePostRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthorizeHandlerInterfaceMock_HandleAuthorizePostRequest_Call) Return() *AuthorizeHandlerInterfaceMock_HandleAuthorizePostRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthorizeHandlerInterfaceMock_HandleAuthorizePostRequest_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *AuthorizeHandlerInterfaceMock_HandleAuthorizePostRequest_Call {
	_c.Run(run)
	return _c
}
