server:
  hostname: "localhost"
  port: 8090

security:
  cert_file: "repository/resources/security/server.cert"
  key_file: "repository/resources/security/server.key"

database:
  identity:
    type: "sqlite"
    path: "repository/database/thunderdb.db"
    options: "_journal_mode=WAL&_busy_timeout=5000"
    max_open_conns: 500
    max_idle_conns: 100
    conn_max_lifetime: 3600

  runtime:
    type: "sqlite"
    path: "repository/database/runtimedb.db"
    options: "_journal_mode=WAL&_busy_timeout=5000"
    max_open_conns: 500
    max_idle_conns: 100
    conn_max_lifetime: 3600

cors:
  allowed_origins:
    - "https://localhost:3000"
    - "https://localhost:9001"
    - "https://localhost:9090"
