-- Table: SP_APP.
CREATE TABLE SP_APP (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APP_NAME VARCHAR(255) NOT NULL,
    APP_ID VARCHAR(36) UNIQUE NOT NULL,
    VERSION VARCHAR(50) NOT NULL
);

-- Table: IDN_OAUTH_CONSUMER_APPS
CREATE TABLE IDN_OAUTH_CONSUMER_APPS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CONSUMER_KEY VARCHAR(255) NOT NULL,
    CONSUMER_SECRET VARCHAR(255) NOT NULL,
    APP_ID VARCHAR(36) NOT NULL REFERENCES SP_APP(APP_ID) ON DELETE CASCADE,
    CALLBACK_URIS TEXT,
    GRANT_TYPES TEXT
);

-- Table: SP_INBOUND_AUTH
CREATE TABLE SP_INBOUND_AUTH (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INBOUND_AUTH_KEY VARCHAR(255) NOT NULL,
    INBOUND_AUTH_TYPE VARCHAR(50) NOT NULL,
    APP_ID VARCHAR(36) NOT NULL REFERENCES SP_APP(APP_ID) ON DELETE CASCADE
);

-- Insert sample data into the tables

INSERT INTO SP_APP (APP_NAME, APP_ID, VERSION) VALUES ('Test SPA', '550e8400-e29b-41d4-a716-446655440000', '1.0');

INSERT INTO IDN_OAUTH_CONSUMER_APPS (CONSUMER_KEY, CONSUMER_SECRET, APP_ID, CALLBACK_URIS, GRANT_TYPES) 
VALUES ('client123', 'secret123', '550e8400-e29b-41d4-a716-446655440000', 'http://example.com/callback', 'client_credentials');

INSERT INTO SP_INBOUND_AUTH (INBOUND_AUTH_KEY, INBOUND_AUTH_TYPE, APP_ID) 
VALUES ('client123', 'oauth2', '550e8400-e29b-41d4-a716-446655440000');
