// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cache

import (
	mock "github.com/stretchr/testify/mock"
)

// NewCacheManagerInterfaceMock creates a new instance of CacheManagerInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheManagerInterfaceMock[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheManagerInterfaceMock[T] {
	mock := &CacheManagerInterfaceMock[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CacheManagerInterfaceMock is an autogenerated mock type for the CacheManagerInterface type
type CacheManagerInterfaceMock[T any] struct {
	mock.Mock
}

type CacheManagerInterfaceMock_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *CacheManagerInterfaceMock[T]) EXPECT() *CacheManagerInterfaceMock_Expecter[T] {
	return &CacheManagerInterfaceMock_Expecter[T]{mock: &_m.Mock}
}

// Clear provides a mock function for the type CacheManagerInterfaceMock
func (_mock *CacheManagerInterfaceMock[T]) Clear() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CacheManagerInterfaceMock_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type CacheManagerInterfaceMock_Clear_Call[T any] struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *CacheManagerInterfaceMock_Expecter[T]) Clear() *CacheManagerInterfaceMock_Clear_Call[T] {
	return &CacheManagerInterfaceMock_Clear_Call[T]{Call: _e.mock.On("Clear")}
}

func (_c *CacheManagerInterfaceMock_Clear_Call[T]) Run(run func()) *CacheManagerInterfaceMock_Clear_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CacheManagerInterfaceMock_Clear_Call[T]) Return(err error) *CacheManagerInterfaceMock_Clear_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *CacheManagerInterfaceMock_Clear_Call[T]) RunAndReturn(run func() error) *CacheManagerInterfaceMock_Clear_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type CacheManagerInterfaceMock
func (_mock *CacheManagerInterfaceMock[T]) Delete(key CacheKey) error {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(CacheKey) error); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CacheManagerInterfaceMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CacheManagerInterfaceMock_Delete_Call[T any] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key CacheKey
func (_e *CacheManagerInterfaceMock_Expecter[T]) Delete(key interface{}) *CacheManagerInterfaceMock_Delete_Call[T] {
	return &CacheManagerInterfaceMock_Delete_Call[T]{Call: _e.mock.On("Delete", key)}
}

func (_c *CacheManagerInterfaceMock_Delete_Call[T]) Run(run func(key CacheKey)) *CacheManagerInterfaceMock_Delete_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 CacheKey
		if args[0] != nil {
			arg0 = args[0].(CacheKey)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CacheManagerInterfaceMock_Delete_Call[T]) Return(err error) *CacheManagerInterfaceMock_Delete_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *CacheManagerInterfaceMock_Delete_Call[T]) RunAndReturn(run func(key CacheKey) error) *CacheManagerInterfaceMock_Delete_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type CacheManagerInterfaceMock
func (_mock *CacheManagerInterfaceMock[T]) Get(key CacheKey) (T, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 T
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(CacheKey) (T, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(CacheKey) T); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(CacheKey) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// CacheManagerInterfaceMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CacheManagerInterfaceMock_Get_Call[T any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key CacheKey
func (_e *CacheManagerInterfaceMock_Expecter[T]) Get(key interface{}) *CacheManagerInterfaceMock_Get_Call[T] {
	return &CacheManagerInterfaceMock_Get_Call[T]{Call: _e.mock.On("Get", key)}
}

func (_c *CacheManagerInterfaceMock_Get_Call[T]) Run(run func(key CacheKey)) *CacheManagerInterfaceMock_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 CacheKey
		if args[0] != nil {
			arg0 = args[0].(CacheKey)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CacheManagerInterfaceMock_Get_Call[T]) Return(v T, b bool) *CacheManagerInterfaceMock_Get_Call[T] {
	_c.Call.Return(v, b)
	return _c
}

func (_c *CacheManagerInterfaceMock_Get_Call[T]) RunAndReturn(run func(key CacheKey) (T, bool)) *CacheManagerInterfaceMock_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

// IsEnabled provides a mock function for the type CacheManagerInterfaceMock
func (_mock *CacheManagerInterfaceMock[T]) IsEnabled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsEnabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// CacheManagerInterfaceMock_IsEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEnabled'
type CacheManagerInterfaceMock_IsEnabled_Call[T any] struct {
	*mock.Call
}

// IsEnabled is a helper method to define mock.On call
func (_e *CacheManagerInterfaceMock_Expecter[T]) IsEnabled() *CacheManagerInterfaceMock_IsEnabled_Call[T] {
	return &CacheManagerInterfaceMock_IsEnabled_Call[T]{Call: _e.mock.On("IsEnabled")}
}

func (_c *CacheManagerInterfaceMock_IsEnabled_Call[T]) Run(run func()) *CacheManagerInterfaceMock_IsEnabled_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CacheManagerInterfaceMock_IsEnabled_Call[T]) Return(b bool) *CacheManagerInterfaceMock_IsEnabled_Call[T] {
	_c.Call.Return(b)
	return _c
}

func (_c *CacheManagerInterfaceMock_IsEnabled_Call[T]) RunAndReturn(run func() bool) *CacheManagerInterfaceMock_IsEnabled_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type CacheManagerInterfaceMock
func (_mock *CacheManagerInterfaceMock[T]) Set(key CacheKey, value T) error {
	ret := _mock.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(CacheKey, T) error); ok {
		r0 = returnFunc(key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CacheManagerInterfaceMock_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type CacheManagerInterfaceMock_Set_Call[T any] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key CacheKey
//   - value T
func (_e *CacheManagerInterfaceMock_Expecter[T]) Set(key interface{}, value interface{}) *CacheManagerInterfaceMock_Set_Call[T] {
	return &CacheManagerInterfaceMock_Set_Call[T]{Call: _e.mock.On("Set", key, value)}
}

func (_c *CacheManagerInterfaceMock_Set_Call[T]) Run(run func(key CacheKey, value T)) *CacheManagerInterfaceMock_Set_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 CacheKey
		if args[0] != nil {
			arg0 = args[0].(CacheKey)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CacheManagerInterfaceMock_Set_Call[T]) Return(err error) *CacheManagerInterfaceMock_Set_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *CacheManagerInterfaceMock_Set_Call[T]) RunAndReturn(run func(key CacheKey, value T) error) *CacheManagerInterfaceMock_Set_Call[T] {
	_c.Call.Return(run)
	return _c
}
